### ISSUE TITLE
Use the new operation GET /datasets/<id>/studies

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#118]
I think now two requests are sent to get the list of studies of dataset: one without `limit` to get the total number of studies and anoter with the `limit` param for pagination. These two request are sent to `GET /datasets/<id>`.

So, there is a new operation to get only the list of studies:
https://github.com/chaimeleon-eu/dataset-service/commit/54cb67e6b45b7968654b29864e56f8edb11abc7c#diff-d1585626c739ccc461efcdc93f4d459e953a91c7c26dcb197c7ce1dde05ba62cR288

In the future, that list will be deleted from the dataset details (i.e. `GET /datasets/<id>`).

That operation returns an object with the total number of studies and other useful info for the pagination control and of course the list of studies.

**Comment by asalic** [comment]
@Palollo you should leave the total number of studies, because it is statistics and helps with the pagination of studies when needed

**Comment by Palollo** [comment]
In the future the list of studies (`studies` property) will be deleted, but not the `studiesCount` property. This is useful to show in the dataset details:
![imagen](https://github.com/chaimeleon-eu/dataset-explorer/assets/10077592/b7b106d8-13ca-4d99-8645-58fe8423c1a5)
But for the pagination control you should call the [new operation](https://chaimeleon-eu.i3m.upv.es/dataset-service/api-doc#tag/datasets/operation/getDatasetStudies) `GET /datasets/{id}/studies` which returns the `total` and all the other required properties:
```
{
    "total": ...,
    "returned": ...,
    "skipped": ...,
    "limit": ...,
    "list": [...]
}
```

**Comment by asalic** [comment]
@Palollo yes, I'm going to use the GET studies operation, but the total will be obtained from the dataset details
