### ISSUE TITLE
Add a new action button to check the integrity of a dataset

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#119]
https://github.com/chaimeleon-eu/dataset-service/commit/8d387a61d2ed18db086b8915839788b7de8b359a#diff-d1585626c739ccc461efcdc93f4d459e953a91c7c26dcb197c7ce1dde05ba62cR315

**Comment by Palollo** [comment]
Please take into account the returned code for succesful operation has been changed later than the commit of the link: 
now it is 200 instead of 201.

**Comment by asalic** [comment]
@Palollo Is there a way  to check if an integrity job is already running for a certain dataset? does the prop "checkIntegrity" from the "allowedActionsForTheUser" field of a dataset takes that into account? It should be nice to inform the user if a check  is underway.
