### ISSUE TITLE
Use the new property `allowedActionsForTheUser`

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#121]
The operation `GET /datasets/<id>/` returns and object which now includes a property `allowedActionsForTheUser`:
https://github.com/chaimeleon-eu/dataset-service/commit/8d387a61d2ed18db086b8915839788b7de8b359a#diff-d1585626c739ccc461efcdc93f4d459e953a91c7c26dcb197c7ce1dde05ba62cR811

That property is similar to the previous `editablePropertiesByTheUser`, which is a list of the exact name of properties that can be changed.
In the case of `allowedActionsForTheUser`, it is a list of words representing actions/operations that the user can do with the dataset. That operations actually are http requests of type POST or DELETE **. The list of possible words and the operation associated for each is in the REST API spec (see the previous link).
** NOTE: the PATCH is already included in `editablePropertiesByTheUser`, i.e. the user can do a PATCH if the list of `editablePropertiesByTheUser` is not empty.

So, currently that new property can be used... 
 - for the logic of whether to show or not the action button `Use on Apps Dashboard`, 
 - and also for  #120 ,
 - and also for  #119 .

**Comment by Palollo** [comment]
and also for #123 .

**Comment by Palollo** [comment]
and also for #134 .

**Comment by Palollo** [comment]
As extended later for other operations (see previous comments), here is the always updated spec of the `DatasetDetails` object with the property `allowedActionsForTheUser`:
https://chaimeleon-eu.i3m.upv.es/dataset-service/api-doc#tag/datasetDetails_schema

**Comment by Palollo** [comment]
and also for #156 .

**Comment by asalic** [comment]
@Palollo Please don't update the same issue with new allowed ops, just create a new issue!!! Appreciated
