### ISSUE TITLE
Add new property `lastIntegrityCheck` of dataset

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#122]
https://github.com/chaimeleon-eu/dataset-service/commit/fdc855634eb5700dc6cbf5f27fc5120a4731aced#diff-d1585626c739ccc461efcdc93f4d459e953a91c7c26dcb197c7ce1dde05ba62cR649

**Comment by asalic** [comment]
fix f2b58fd07f42e130f63de8c74fb0bd4ae5381cc5
