### ISSUE TITLE
Add new metadata fields and adjust description of some of the current fields

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#124]
- **Age range**: 
   - Change tooltip ", DICOM tag (0010, 1010)"  -->  ", DICOM tag (0010, 1010) or subject clinical data (inclusion_criteria.age_at_diagnosis or .age_at_baseline)"
   - Add the new property [`ageNullCount`](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L956), for example as a note in brackets like this: 
       ```
       Age range
           from 64 to 76 years (2 studies with unkown age)
       ```
- **Gender**: 
   - Change tooltip ", DICOM tag (0010, 0040)"  -->  ", DICOM tag (0010, 0040) or subject clinical data (patient_data.gender)"
   - Add the new property [`sexCount`](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L969), for example as a number in brackets like this: 
       ```
       Gender (#studies)
           Male (#143), Female (#212)
       ```
- **Modality**: 
   - Add the new property [`modalityCount`](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L1001), for example as a number in brackets like this: 
       ```
       Modality (#studies)
           PT (#143), CT (#212)
       ```
- **Body part**: 
   - Add the new property [`bodyPartCount`](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L985), for example as a number in brackets like this: 
       ```
       Body part (#studies)
           BRAIN (#143), LUNG (#212)
       ```
- **Manufacturer**: This is a [new property](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L1007) to add similar to "Modality". There is also the property [`manufacturerCount`](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L1016). 
  Example:
  ```
  Manufacturer (#studies)
      Philips (#143), Siemens (#212)
  ```
- **Year of diagnosis**:  There are new properties [diagnosisYearLow and diagnosisYearHigh](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L1022) which are similar to "AgeLow" and "AgeHigh". There is also the property [`diagnosisYearNullCount`](https://github.com/chaimeleon-eu/dataset-service/blob/92007fd660540e63cf495192aedf81d3c2cb1580/API-reference-v1.yaml#L1032). 
  Example:
  ```
  Year of diagnosis
      from 2008 to 2020 (2 studies with unkown year)
  ```

**Comment by asalic** [comment]
fix 2118b2a7bd230ff7c7986ca323d1d069e1499bc7
