### ISSUE TITLE
Use the new operation GET /datasets/<id>/accessHistory

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#134]
Described here:
https://chaimeleon-test.grycap.i3m.upv.es/dataset-service/api-doc#tag/datasets/operation/getDatasetAccessHistory

Suggested place to add:
![imagen](https://github.com/chaimeleon-eu/dataset-explorer/assets/10077592/8807d71e-74c0-4c81-957f-2c2827446281)

**Comment by asalic** [comment]
fix c278c6723d3e0aaa57a6d0101339ecba8c378fe7
