### ISSUE TITLE
Go to the first page when filters change

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#140]
When some filter is added, changed or removed, the number of items change in the list of datasets, so the number of pages also change and then the current page can become empty. So we can stay in the page 8 but only there are items to fill the first 3 pages.
The proposal is to go to the first page whenever a filter is added, changed or removed.

**Comment by asalic** [comment]
fix dbb1fb16813864e3822f1c816a281726ff04082d
