### ISSUE TITLE
Add new metadata field "Size" in dataset and study

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#144]
In the following commit a new property `sizeInBytes` has been added to the objects returned by `GET /datasets` and `GET /datasets/{id}/studies`:
https://github.com/chaimeleon-eu/dataset-service/commit/5728b7e391434fc3b213abe5fc4af8796b351898#diff-016c18f27ce25e8b5a40d9820840577c6e5b634b75e84a025cd58191f6dc77d0

In case of dataset the new property (suggested: "Total size:") should be added to the metadata frame at right side of the dataset details page. For example at the end of the rest of metada fields to add mentioned in #124 .

In case of study just a new column "Size" should be added to the table.

In both cases, the value should be converted dinamically to the most appropiate unit, i.e. KB, MB, GB.

**Comment by asalic** [comment]
fix fc9f5fc0caa2556f56766bcc2604149e509bd6d7
