### ISSUE TITLE
Adjust the call to `GET /datasets`

### ISSUE THREAD

**Issue by Palollo** [chaimeleon-eu/dataset-explorer#145]
The current call to that operation is:
```
GET https://chaimeleon-eu.i3m.upv.es/dataset-service/api/datasets?skip=0&modLimit=30&searchString=&sortBy=creationDate&sortDirection=descending&v2=true
```
But the param `modLimit` is unrecognized and so ignored, it should be just `limit`.
And the param `v2` is no more needed and so ignored also: the pagination info is included now by default.

**Comment by asalic** [comment]
fix 16865e44a9cb4e3cb6c1a459ddb3c9e0df44071f
